const SM_STATES_AXIOS_REQ  = {
	IS_IDEAL: "IS_IDEAL",
	IS_TRIGGERED : "IS_TRIGGERED",
	IS_FAILED: "IS_FAILED",
	IS_SUCCESSFUL: "IS_SUCCESSFUL",
	IS_SUCCESS_BUT_NO_DATA: "IS_SUCCESS_BUT_NO_DATA",
}

export default SM_STATES_AXIOS_REQ